import:
    build: .
    env_file: .env
    volumes:
        - ./src/import.js:/data/src/import.js:ro
        - ./archive/:/data/archive/
    links:
        - couchdb
couchdb:
    image: frodenas/couchdb:1.6
    env_file: .env
    ports:
        - "5984:5984"
